# Generated by Django 5.1.5 on 2025-05-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentacion_auditores', '0007_alter_actaauditoria_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('checkpoint_iaf_md4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.BooleanField(default=False)),
                ('no_cumple', models.BooleanField(default=False)),
                ('no_aplica', models.BooleanField(default=False)),
                ('aspecto_mejora', models.BooleanField(default=False)),
                ('concepto_mejora', models.TextField(blank=True)),
                ('concepto_no_conformidad', models.TextField(blank=True)),
                ('evidencia', models.CharField(blank=True, choices=[('documental', 'Evidencia Documental'), ('fotografica', 'Evidencia Fotográfica'), ('audiovisual', 'Evidencia Audiovisual'), ('documental_fotografica', 'Evidencia Documental y Fotográfica'), ('documental_audiovisual', 'Evidencia Documental y Audiovisual'), ('fotografica_audiovisual', 'Evidencia Fotográfica y Audiovisual'), ('documental_fotografica_audiovisual', 'Evidencia Documental, Fotográfica y Audiovisual')], max_length=100)),
                ('concepto_evidencia', models.TextField(blank=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='documentacion_auditores.actaauditoria')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejecucion_auditoria.requisitoauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsanado', models.BooleanField(default=False)),
                ('comentario_subsanacion', models.TextField(blank=True)),
                ('fecha_subsanacion', models.DateField(blank=True, null=True)),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ejecucion_auditoria.ejecucionrequisito')),
            ],
        ),
    ]
