# Generated by Django 5.1.5 on 2025-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_auditoria', '0002_ejecucionrequisito_subsanado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionrequisito',
            name='como_se_subsano',
            field=models.TextField(blank=True, verbose_name='¿Cómo se subsanó la no conformidad?'),
        ),
    ]
