# Generated by Django 5.1.5 on 2025-05-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion_auditoria', '0003_ejecucionrequisito_como_se_subsano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionrequisito',
            name='aspecto_mejora',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionrequisito',
            name='cumple',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionrequisito',
            name='no_aplica',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
