# Generated by Django 5.1.5 on 2025-05-07 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '0003_alter_programacionauditoria_fecha_programacion_etapa1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_legal_nombre', models.CharField(max_length=255)),
                ('representante_legal_cargo', models.CharField(max_length=100)),
                ('firma_representante', models.ImageField(blank=True, null=True, upload_to='documentacion/firmas/')),
                ('firma_auditor', models.ImageField(blank=True, null=True, upload_to='documentacion/firmas/')),
                ('asistencia', models.TextField(help_text='Lista de asistentes con nombre, cargo y firmas')),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programacion.programacionauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenteActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('firma_apertura', models.ImageField(blank=True, null=True, upload_to='documentacion/firmas/')),
                ('firma_cierre', models.ImageField(blank=True, null=True, upload_to='documentacion/firmas/')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='documentacion_auditores.actaauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaf_md4_verificado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField()),
                ('archivo_vehiculos_instructores', models.FileField(blank=True, null=True, upload_to='documentacion/vehiculos_instructores/')),
                ('auditor', models.ForeignKey(limit_choices_to={'groups__name': 'Auditores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programacion.programacionauditoria')),
            ],
        ),
    ]
