# Generated by Django 5.1.5 on 2025-05-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0001_initial'),
        ('programacion', '0004_remove_auditor_correo_remove_auditor_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=255)),
                ('requisito', models.TextField(blank=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.nivelauditoriacea')),
            ],
        ),
        migrations.CreateModel(
            name='HoraActividadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion_auditores.actividadcea')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_actividades', to='documentacion_auditores.planauditoria')),
            ],
        ),
    ]
