# Generated by Django 5.1.5 on 2025-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0002_actividadcea_horaactividadplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadcea',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='actividadcea',
            name='requisito',
        ),
        migrations.AddField(
            model_name='actividadcea',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Proceso/Actividad/Requisito por Auditar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadcea',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
