# Generated by Django 5.1.5 on 2025-05-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0003_remove_actividadcea_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_vehiculos_instructores', models.FileField(upload_to='vehiculos_instructores/')),
            ],
        ),
    ]
