# Generated by Django 5.1.5 on 2025-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0004_vehiculoinstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='planauditoria',
            name='aprobado_por_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planauditoria',
            name='fecha_aprobacion_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
