# Generated by Django 5.1.5 on 2025-05-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0005_planauditoria_aprobado_por_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaauditoria',
            name='programacion',
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='documentacion_auditores.planauditoria'),
        ),
    ]
