# Generated by Django 5.1.5 on 2025-05-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0006_remove_actaauditoria_programacion_actaauditoria_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaauditoria',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='documentacion_auditores.planauditoria'),
        ),
    ]
