# Generated by Django 5.1.5 on 2025-05-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0007_alter_actaauditoria_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='fecha_inicio_subsanacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
