# Generated by Django 5.1.5 on 2025-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0008_actaauditoria_fecha_inicio_subsanacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='recomendaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
