# Generated by Django 5.1.5 on 2025-05-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0009_actaauditoria_recomendaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaauditoria',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
