# Generated by Django 5.1.5 on 2025-05-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0010_alter_actaauditoria_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='aspectos_relevantes',
            field=models.TextField(blank=True, verbose_name='Aspectos relevantes del servicio auditado'),
        ),
    ]
