# Generated by Django 5.1.5 on 2025-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0011_actaauditoria_aspectos_relevantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaauditoria',
            name='aspectos_relevantes',
        ),
    ]
