# Generated by Django 5.1.5 on 2025-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0012_remove_actaauditoria_aspectos_relevantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='aspectos_relevantes',
            field=models.TextField(blank=True, verbose_name='Aspectos relevantes del servicio auditado'),
        ),
    ]
