# Generated by Django 5.1.5 on 2025-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_auditores', '0013_actaauditoria_aspectos_relevantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaauditoria',
            name='muestra_normal',
            field=models.PositiveIntegerField(default=0, verbose_name='Muestra (Normal)'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='muestra_reducido',
            field=models.PositiveIntegerField(default=0, verbose_name='Muestra (Reducido)'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='poblacion_normal',
            field=models.PositiveIntegerField(default=0, verbose_name='Población (Normal)'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='poblacion_reducido',
            field=models.PositiveIntegerField(default=0, verbose_name='Población (Reducido)'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='universo_normal',
            field=models.PositiveIntegerField(default=0, verbose_name='Universo (Normal)'),
        ),
        migrations.AddField(
            model_name='actaauditoria',
            name='universo_reducido',
            field=models.PositiveIntegerField(default=0, verbose_name='Universo (Reducido)'),
        ),
    ]
