# Generated by Django 5.1.5 on 2025-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('representante_legal', models.CharField(max_length=100)),
                ('cedula_ciudadania', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('representante_organismo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nivel_cea', models.CharField(max_length=50)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('cantidad_instructores', models.IntegerField()),
                ('certificado_conformidad', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=100)),
                ('nombre_ente_certificador', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
