# Generated by Django 5.1.5 on 2025-01-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_solicitud',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
