# Generated by Django 5.1.5 on 2025-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_cliente_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
