# Generated by Django 5.1.5 on 2025-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_cliente_cantidad_instructores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cantidad_vehiculos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
