# Generated by Django 5.1.5 on 2025-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_categoria_alter_cliente_certificado_conformidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
