# Generated by Django 5.1.5 on 2025-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_cliente_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('FORMACION DE INSTRUCTORES A1', 'FORMACION DE INSTRUCTORES A1'), ('FORMACION DE INSTRUCTORES A2', 'FORMACION DE INSTRUCTORES A2'), ('FORMACION DE INSTRUCTORES B1', 'FORMACION DE INSTRUCTORES B1'), ('FORMACION DE INSTRUCTORES B2', 'FORMACION DE INSTRUCTORES B2'), ('FORMACION DE INSTRUCTORES B3', 'FORMACION DE INSTRUCTORES B3'), ('FORMACION DE INSTRUCTORES C1', 'FORMACION DE INSTRUCTORES C1'), ('FORMACION DE INSTRUCTORES C2', 'FORMACION DE INSTRUCTORES C2'), ('FORMACION DE INSTRUCTORES C3', 'FORMACION DE INSTRUCTORES C3')], max_length=40, unique=True),
        ),
    ]
