# Generated by Django 5.1.5 on 2025-02-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0012_remove_cotizacion_nivel_cea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('iaf_md4_confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAuditoriaCEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=200, unique=True)),
                ('dias_etapa1', models.FloatField(default=0.5)),
                ('dias_etapa2', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programacion_etapa1', models.DateField()),
                ('hora_etapa1', models.TimeField(default='00:00')),
                ('iaf_md4_confirmado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('auditores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.auditor')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
                ('nivel_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.nivelauditoriacea')),
            ],
        ),
        migrations.CreateModel(
            name='FechaEtapa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default='00:00')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_etapa2', to='programacion.programacionauditoria')),
            ],
        ),
    ]
