# Generated by Django 5.1.5 on 2025-02-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='fecha_programada',
        ),
        migrations.AddField(
            model_name='programacion',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Programada', 'Programada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='programacion',
            name='fecha_auditoria',
            field=models.DateField(blank=True, null=True),
        ),
    ]
