# Generated by Django 5.1.5 on 2025-02-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.nivelauditoriacea'),
        ),
    ]
