# Generated by Django 5.1.5 on 2025-02-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_alter_programacionauditoria_nivel_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
