# Generated by Django 5.1.5 on 2025-05-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_alter_programacionauditoria_fecha_programacion_etapa1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='auditor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='auditor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
