# Generated by Django 5.1.5 on 2025-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_rename_fecha_auditoria_programacion_fecha_etapa_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacion',
        ),
    ]
