# Generated by Django 5.1.5 on 2025-02-12 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0007_alter_cotizacion_estado'),
        ('programacion', '0004_delete_programacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_etapa_1', models.DateField(blank=True, null=True)),
                ('hora_etapa_1', models.TimeField(blank=True, null=True)),
                ('dias_auditoria_etapa_1', models.DecimalField(decimal_places=1, default=0.5, max_digits=3)),
                ('fecha_etapa_2', models.JSONField(blank=True, null=True)),
                ('hora_etapa_2', models.TimeField(blank=True, null=True)),
                ('dias_auditoria_etapa_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Programada', 'Programada')], default='Pendiente', max_length=20)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
            ],
        ),
    ]
