# Generated by Django 5.1.5 on 2025-02-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0006_programacionauditoria_delete_programacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacionauditoria',
            old_name='hora_etapa2',
            new_name='hora_etapa2_1',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2',
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='hora_etapa2_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='hora_etapa2_3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
