# Generated by Django 5.1.5 on 2025-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0007_rename_hora_etapa2_programacionauditoria_hora_etapa2_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacionauditoria',
            old_name='hora_etapa2_1',
            new_name='hora_etapa2',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_1',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_2',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2_3',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='hora_etapa2_2',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='hora_etapa2_3',
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa2',
            field=models.JSONField(default=list),
        ),
    ]
