# Generated by Django 5.1.5 on 2025-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0009_programacionauditoria_dias_auditoria_etapa1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
