# Generated by Django 5.1.5 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0010_alter_programacionauditoria_fecha_programacion_etapa1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelCEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dias_etapa1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dias_etapa2', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
