# Generated by Django 5.1.5 on 2025-02-18 17:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0011_nivelcea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('iaf_md4_confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAuditoriaCEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2'), ('Nivel 3', 'Nivel 3'), ('Nivel 3 con Formación de Instructores', 'Nivel 3 con Formación de Instructores')], max_length=50, unique=True)),
                ('dias_etapa1', models.DecimalField(decimal_places=1, default=0.5, max_digits=3)),
                ('dias_etapa2', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='NivelCEA',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='dias_auditoria_etapa1',
        ),
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='dias_auditoria_etapa2',
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa1',
            field=models.DateField(default=datetime.date(2025, 2, 18)),
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='auditores',
            field=models.ManyToManyField(related_name='programaciones', to='programacion.auditor'),
        ),
        migrations.AddField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.nivelauditoriacea'),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
