# Generated by Django 5.1.5 on 2025-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0012_auditor_nivelauditoriacea_delete_nivelcea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
        ),
        migrations.AlterField(
            model_name='auditor',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='nivelauditoriacea',
            name='dias_etapa1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nivelauditoriacea',
            name='dias_etapa2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nivelauditoriacea',
            name='nivel',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='fecha_programacion_etapa1',
            field=models.DateField(),
        ),
    ]
