# Generated by Django 5.1.5 on 2025-02-19 15:17

import django.db.models.deletion
import programacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0014_remove_programacionauditoria_fecha_programacion_etapa2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='cedula',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fechaetapa2',
            name='dias_auditoria',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nivelauditoriacea',
            name='nivel',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='dias_etapa1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
            field=models.ForeignKey(default=programacion.models.obtener_nivel_predeterminado, on_delete=django.db.models.deletion.CASCADE, to='programacion.nivelauditoriacea'),
        ),
    ]
