# Generated by Django 5.1.5 on 2025-02-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0015_alter_auditor_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='programacion.nivelauditoriacea'),
        ),
    ]
