# Generated by Django 5.1.5 on 2025-02-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0016_permitir_null_nivel_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionauditoria',
            name='nivel_auditoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programacion.nivelauditoriacea'),
            preserve_default=False,
        ),
    ]
