# Generated by Django 5.1.5 on 2025-02-09 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Otorgamiento Inicial', 'Otorgamiento Inicial'), ('Seguimiento', 'Seguimiento'), ('Renovación de la Certificación', 'Renovación de la Certificación'), ('Vigilancia Ordinaria', 'Vigilancia Ordinaria'), ('Vigilancia Extraordinaria', 'Vigilancia Extraordinaria'), ('Ampliación de Alcance', 'Ampliación de Alcance'), ('Reducción de Alcance', 'Reducción de Alcance')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.CharField(help_text='Formato: XXXX-X', max_length=10, unique=True)),
                ('fecha_cotizacion', models.DateField(auto_now_add=True)),
                ('dias_auditoria_etapa_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('dias_auditoria_etapa_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('precio_neto', models.DecimalField(decimal_places=2, help_text='Valor sin IVA', max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, help_text='IVA aplicado', max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Precio Neto + IVA', max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
                ('tipo_servicio', models.ManyToManyField(to='cotizaciones.tiposervicio')),
            ],
        ),
    ]
