# Generated by Django 5.1.5 on 2025-02-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='iva',
            new_name='precio_iva',
        ),
    ]
