# Generated by Django 5.1.5 on 2025-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_rename_iva_cotizacion_precio_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
