# Generated by Django 5.1.5 on 2025-02-10 21:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_tiposervicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cotizada', 'Cotizada')], default='Pendiente', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='precio_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA (19%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total con IVA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(choices=[('Otorgamiento Inicial', 'Otorgamiento Inicial'), ('Seguimiento', 'Seguimiento'), ('Renovación de la Certificación', 'Renovación de la Certificación'), ('Vigilancia Ordinaria', 'Vigilancia Ordinaria'), ('Vigilancia Extraordinaria', 'Vigilancia Extraordinaria'), ('Ampliación de Alcance', 'Ampliación de Alcance'), ('Reducción de Alcance', 'Reducción de Alcance')], max_length=50, unique=True),
        ),
    ]
