# Generated by Django 5.1.5 on 2025-02-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_solicitud_alter_cotizacion_precio_iva_and_more'),
        ('solicitudes', '0010_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizaciones', to='solicitudes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nit',
            field=models.CharField(blank=True, help_text='Número de NIT del cliente', max_length=20, null=True),
        ),
    ]
