# Generated by Django 5.1.5 on 2025-02-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_solicitud_cliente_solicitud_nit'),
        ('solicitudes', '0010_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Programado', 'Programado')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='solicitudes.cliente'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
