# Generated by Django 5.1.5 on 2025-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_alter_cotizacion_estado_alter_solicitud_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
