# Generated by Django 5.1.5 on 2025-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Programada', 'Programada')], default='Pendiente', max_length=20),
        ),
    ]
