# Generated by Django 5.1.5 on 2025-02-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_alter_cotizacion_fecha_cotizacion'),
        ('solicitudes', '0010_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='solicitudes.solicitud'),
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
