# Generated by Django 5.1.5 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_alter_cotizacion_solicitud_delete_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='nivel_cea',
            field=models.CharField(blank=True, choices=[('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2'), ('Nivel 3', 'Nivel 3'), ('Nivel 3 con Formación de Instructores', 'Nivel 3 con Formación de Instructores')], max_length=50, null=True),
        ),
    ]
