# Generated by Django 5.1.5 on 2025-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_cotizacion_nivel_cea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='nivel_cea',
        ),
    ]
