# Generated by Django 5.1.5 on 2025-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_remove_cotizacion_nivel_cea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_servicio',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
